image:
  file: Dockerfile

tasks:
  - name: Initialize Conda Environment
    init: |
      echo "Conda env is ready."
      git clone https://github.com/grunwaldlab/pathogensurveillance.git /workspace/pathogensurveillance
    command: |
      conda activate nf-core
      cd /workspace/pathogensurveillance
      nextflow run main.nf --help

ports:
  - port: 8080
    onOpen: ignore

